
agent_name: lail_cl

agent:
  _target_: agents.lail_cl.LailClAgent
  obs_shape: ??? # to be specified later
  obs_sensor_shape: ??? #to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  use_tb: ${use_tb}
  reward_d_coef: 2.0
  discriminator_lr: ${discriminator_lr}
  spectral_norm_bool: ${spectral_norm_bool}
  check_every_steps: ${check_every_steps}
  pretrained_encoder_path: ??? #to be specified later
  encoder_lr_scale: ${encoder_lr_scale}
  pretrained_encoder: ${pretrained_encoder}
  pretrained_encoder_model_name: ${pretrained_encoder_model_name}
  GAN_loss: ${GAN_loss}
  from_dem: ${from_dem}
  RL_plus_IL: ${RL_plus_IL}
  train_encoder_w_critic: ${train_encoder_w_critic}
  CL_data_type: ${CL_data_type}
  add_aug_anchor_and_positive: true
  aug_type: ${aug_type}
  apply_aug: ${apply_aug}
